"use client";

import { useState } from "react";

const plans = { INR: [{ name: "Starter", price: "₹29,999", note: "For small businesses building a foundation", features: ["Brand identity essentials", "Social media management - 2 platforms", "Graphic design - 8 assets/mo", "Content creation & modulation", "Video editing", "WhatsApp & email marketing", "Online reputation management", "Monthly performance report"] }, { name: "Growth", price: "₹49,999", note: "For businesses ready to scale with paid media", features: ["Everything in Starter", "AI video generation", "Meta & Google Ads management", "SEO fundamentals + WhatsApp marketing", "Bi-weekly strategy calls"] }, { name: "Enterprise", price: "₹69,999", note: "Full-suite growth & brand-trust partner", features: ["Everything in Growth", "LinkedIn B2B marketing & ABM", "AI automation + CRM integration", "Online reputation management", "Dedicated account manager"] }], USD: [{ name: "Starter", price: "$349", note: "For small businesses building a foundation", features: ["Brand identity essentials", "Social media management - 2 platforms", "Graphic design - 8 assets/mo", "Content creation & modulation", "Video editing", "WhatsApp & email marketing", "Online reputation management", "Monthly performance report"] }, { name: "Growth", price: "$599", note: "For businesses ready to scale with paid media", features: ["Everything in Starter", "AI video generation", "Meta & Google Ads management", "SEO fundamentals + WhatsApp marketing", "Bi-weekly strategy calls"] }, { name: "Enterprise", price: "$849", note: "Full-suite growth & brand-trust partner", features: ["Everything in Growth", "AI video generation", "LinkedIn B2B marketing & ABM", "AI automation + CRM integration", "Online reputation management", "Dedicated account manager"] }] };
const services = [["Branding & Creative Kit", "₹35,000 / $399", "one-time"], ["Web Development", "₹45,000 / $549", "starting"], ["Graphic Designing", "₹15,000 / $179", "/month"], ["Content Creation & Modulation", "₹20,000 / $239", "/month"], ["Video Editing", "₹18,000 / $219", "/month"], ["Social Media Marketing", "₹22,000 / $259", "/month"], ["Meta, Google & LinkedIn Ads", "₹20,000 / $239", "/month"], ["LinkedIn Marketing", "₹25,000 / $299", "/month"], ["WhatsApp Marketing", "₹15,000 / $179", "/month"], ["SEO & GEO", "₹20,000 / $239", "/month"], ["Automation with AI", "₹30,000 + ₹10k / $349 + $119", "setup + /month"], ["Email Marketing", "₹12,000 / $139", "/month"]];

export default function PricingPage() {
  const [currency, setCurrency] = useState<"INR" | "USD">("INR");
  return <main className="pricing-page"><header className="pricing-header"><a className="mini-logo" href="/"><img src="/shinrai-logo.png" alt="Shinrai Connect" /> <span>SHINRAI CONNECT<small>TRUST · STRATEGY · GROWTH</small></span></a><a className="header-button" href="/contact">Book free session <span>↗</span></a></header><section className="pricing-hero"><p className="eyebrow">Simple · Transparent · Scalable</p><h1>Pricing built to fit<br /><em>your growth stage.</em></h1><p>Choose a monthly growth partnership, or build your own plan a la carte. No lock-ins, no hidden fees.</p><div className="currency-switch"><button className={currency === "INR" ? "selected" : ""} onClick={() => setCurrency("INR")}>INR</button><button className={currency === "USD" ? "selected" : ""} onClick={() => setCurrency("USD")}>USD</button></div></section><section className="plans-section"><p className="eyebrow">Monthly growth partnerships</p><h2>Pick your growth tier.</h2><div className="plans-grid">{plans[currency].map((plan, index) => <article className={index === 1 ? "plan featured-plan" : "plan"} key={plan.name}>{index === 1 && <b className="popular">Most popular</b>}<h3>{plan.name}</h3><p>{plan.note}</p><strong>{plan.price}<small>/month</small></strong><a href="/contact">Choose {plan.name} ↗</a><ul>{plan.features.map((feature) => <li key={feature}>+ {feature}</li>)}</ul></article>)}</div></section><section className="services-pricing"><p className="eyebrow">A la carte services</p><h2>Build your own mix.</h2><div className="a-la-carte">{services.map(([name, price, note]) => <article key={name}><div><h3>{name}</h3><p>Focused service built around measurable growth.</p></div><strong>{currency === "INR" ? price.split(" /")[0] : price.split(" /")[1] || price}<small>{note}</small></strong></article>)}</div></section><section className="pricing-contact"><p className="eyebrow">Let&apos;s connect. Let&apos;s grow.</p><h2>Every plan starts with a<br /><em>free strategy session.</em></h2><a className="dark-button" href="/contact">Start the conversation ↗</a><small>Prices shown are indicative starting rates, exclusive of ad spend and applicable taxes. Final quotes are scoped to your goals.</small></section><footer className="site-footer"><a className="mini-logo" href="/"><img src="/shinrai-logo.png" alt="Shinrai Connect" /><span>SHINRAI CONNECT<small>TRUST · STRATEGY · GROWTH</small></span></a><span>6366850605 · shinraiconnect@gmail.com</span></footer></main>;
}
