const serviceGroups = [
  { title: "Brand Identity & Digital Engineering", items: [["Branding & Creative Kit", "Complete brand identity design, logo systems, guidelines, typography, color palettes, and collateral."], ["Web Development", "High-converting responsive websites, landing pages, and web applications built for speed and conversion."], ["Graphic Designing", "Custom visual assets, advertising creatives, promotional materials, infographics, and presentations."]] },
  { title: "Creative Production & Social Engine", items: [["Content Creation & Modulation", "Multi-platform content strategy, copywriting, storyboarding, and messaging tailored to your audience."], ["Video Editing", "High-retention reels, Shorts, promos, and video ads styled with dynamic motion graphics."], ["Social Media Marketing", "Organic channel management, content calendars, community growth, and audience engagement."]] },
  { title: "Paid Acquisition & Conversions", items: [["Meta, Google & LinkedIn Ads", "Targeted PPC campaigns, retargeting funnels, and high-ROI ad spend management."], ["LinkedIn Marketing", "B2B lead generation, thought leadership, account-based marketing, and corporate outreach."], ["WhatsApp Marketing", "Direct-to-messaging funnels, broadcast campaigns, automated chat flows, and lead nurturing."]] },
  { title: "Search, Automation & Outreach", items: [["SEO & GEO", "Search and generative-engine optimization to rank your brand across Google and modern AI discovery."], ["Automation with AI", "Custom AI workflows, CRM integrations, auto-responders, and automated lead routing."], ["Email Marketing", "Cold outreach, automated drip sequences, newsletters, and customer retention campaigns."]] },
  { title: "Trust, Intelligence & Audits", items: [["Online Reputation Management", "Proactive review generation, sentiment tracking, and crisis management that protects brand trust."], ["Analytics, Reports & Audits", "Marketing audits, real-time dashboards, ROI tracking, and clear actionable growth insights."]] },
];

export default function ServicesPage() {
  return <main className="standalone-page services-page"><header className="simple-page-header"><a className="mini-logo" href="/"><img src="/shinrai-logo.png" alt="Shinrai Connect" /><span>SHINRAI CONNECT<small>TRUST · STRATEGY · GROWTH</small></span></a><a className="header-button" href="/contact">Book free session <span>↗</span></a></header><section className="services-hero"><p className="eyebrow">Our services</p><h1>Full-suite marketing<br /><em>&amp; creative services.</em></h1><p>Creative engineering, paid acquisition, and AI automation built to scale businesses predictably.</p></section><div className="service-groups">{serviceGroups.map((group, groupIndex) => <section className="service-group" key={group.title}><div><span className="group-number">0{groupIndex + 1}</span><h2>{group.title}</h2></div><div className="service-items">{group.items.map(([name, text]) => <article key={name}><span>↗</span><div><h3>{name}</h3><p>{text}</p></div></article>)}</div></section>)}</div><section className="services-cta"><p className="eyebrow">Ready to grow?</p><h2>Let&apos;s build<br /><em>what&apos;s next.</em></h2><a className="dark-button" href="/contact">Start a conversation ↗</a></section></main>;
}
